Mutating webhooks
wave-k8s/wave pull request #155
Opened 2024-04-29 23:37 UTC by jabdoa2

Implement mutating webhooks to reduce the number or restarts in new deployments when configmaps and secrets already exist.

On top of #154.

2024-04-30 11:57 UTC, jabdoa2 commented
I tested this on a cluster and it works fine. Fixed two issues which I noticed during testing.

2024-05-01 18:29 UTC, toelke requested changes
Let me get this straight: Before this commit a deployment referencing a non-exiteant CM would be stuck at ContainerCreating stuck in k8s, but wave could start watching for the CM immediately and add the hash once it exists. After this PR wave holds the Pod in Pending until the cm exists, so that it will never run without the annotation?

2024-05-01 18:29 UTC, toelke commented on pkg/controller/daemonset/daemonset_controller_test.go
> +			// Create a deployment and wait for it to be reconciled
```suggestion
			// Create a daemonset and wait for it to be reconciled
```

2024-05-01 18:29 UTC, toelke commented on pkg/controller/statefulset/statefulset_controller_test.go
> +			// Create a deployment and wait for it to be reconciled
```suggestion
			// Create a statefulset and wait for it to be reconciled
```

2024-05-01 19:49 UTC, jabdoa2 commented
> Let me get this straight: Before this commit a deployment referencing a non-exiteant CM would be stuck at ContainerCreating stuck in k8s, but wave could start watching for the CM immediately and add the hash once it exists. After this PR wave holds the Pod in Pending until the cm exists, so that it will never run without the annotation?

Multiple cases:

1. Before
2. Without Webhooks (still an option after the change)
3. With Webhooks

a) All required CMs/secrets exist before the deployment
b) An optional secret is created after (a)
c) At least on required CMs/secret does not exist before the deployment (typical helm install case)

a) All required CMs/secrets exist before the deployment
1 + 2 Before and Without webhooks
- Deployment is created
- Deployment is scheduled without annotation and pods are created
- Wave edits the deployment and add the annotation
- Due to Kubernetes pod lifecycle pods start up and then shutdown
- A rolling update is performed by the deployment controller
- All pods are recreated and restarted

3. With webhooks
- When deployment is created the webhook adds the hash as annotation
- Deployment is scheduled with annotation and pods are created
- Wave reconciles the deployment and starts watching all children
- No restarts occur

b) An optional secret is created
1. Before
- Wave will reconcile a deployment every 10 minutes. If that happens the hash is updated

2 + 3: With or Without webhooks
- We watch all secrets (even not-yet-existing ones) and wave reconciles instantly

c) At least on required CMs/secret does not exist before the deployment (typical helm install case)
1. Before
- Deployment is scheduled without annotation and pods are created
- Pods are stuck in ContainerCreating (due to missing CM/secret)
- Wave fails to read all required children and will run into exponential backoff trying
- CM is added
- Pods start up with the latest CM and are basically up to date
- Eventually, wave reconciles (can take quite a while due to exponential backoff) and edits the deployment to add the annotation
- A rolling update is performed by the deployment controller
- All pods are recreated and restarted

2. Without webhooks
- Deployment is scheduled without annotation and pods are created
- Pods are stuck in ContainerCreating (due to missing CM/secret)
- Wave starts watching all children (including non-existing CMs/secrets)
- CM is added
- Pods start up with the latest CM and are basically up to date
- Wave is instantly starting a reconcile (due to our watch) and edits the deployment to add the annotation
- A rolling update is performed by the deployment controller
- All pods are recreated and restarted

3. With webhooks
- When deployment is created the webhook unsets the kubernetes (pod) scheduler and adds an annotates to store the previous scheduler
- Pods are created but stay pending as there is not scheduler which can schedule them
- Wave reconciles the deployment and starts watching all children (including non-existing CMs/secrets)
- CM is added
- Due to the watch wave starts reconciling the deployment. It notices that all children exists and adds the hash annotation. It also restores the previous scheduler
- A rolling update is performed by the deployment controller
- Pending pods can be instantly replaces with new pods
- All are created and start up
- No restarts occur

To summarize:
- If you do not use webhooks wave behaves slightly better than before (when adding CMs/secrets after the deployment). However, the number of restarts is mostly the same.
- With webhooks we can prevent pod restarts in common scenarios. This reduces stress on the cluster saves a lot of resources

We could decide the make the scheduler trick optional. Webhooks would still have advantages for case (a). However, for us case (c) is far more common. We often install helm charts so this is quite common.

2024-05-02 09:28 UTC, toelke submitted a review, later dismissed

2024-05-02 09:29 UTC, toelke commented
Thank you for that detailed answer.

LGTM, but: Is the scheduler name `invalid` somehow reserved? Could I have a stupid cluster with a valid scheduler called `invalid`? If yes, I think I would prefer to call the invalid scheduler `wave.pusher.com/invalid`.

2024-05-02 10:50 UTC, toelke approved these changes

2024-05-02 10:50 UTC, merged

2024-05-02 10:51 UTC, toelke commented
Should we do a release today or do you have any more changes in the pipeline?